-------------------------회원테이블 생성
CREATE TABLE MEMBERS (
    MNO NUMBER CONSTRAINT MEMBERS_MNO_UK UNIQUE,
    MID VARCHAR2(40) CONSTRAINT MEMBERS_MID_PK PRIMARY KEY,
    PWD VARCHAR2(100) NOT NULL,
    MNAME VARCHAR2(50) NOT NULL,
    BIRTHDATE DATE NOT NULL,
    EMAIL VARCHAR2(40) NOT NULL,
    CRE_DATE DATE NOT NULL,
    MOD_DATE DATE NOT NULL
);

COMMENT ON TABLE MEMBERS IS '회원기본정보';
COMMENT ON COLUMN MEMBERS.MNO IS '회원번호';
COMMENT ON COLUMN MEMBERS.MID IS '아이디';
COMMENT ON COLUMN MEMBERS.PWD IS '비밀번호';
COMMENT ON COLUMN MEMBERS.MNAME IS '이름';
COMMENT ON COLUMN MEMBERS.BIRTHDATE IS '생년월일';
COMMENT ON COLUMN MEMBERS.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBERS.CRE_DATE IS '가입일';
COMMENT ON COLUMN MEMBERS.MOD_DATE IS '회원정보변경일';

-------------------------게시판테이블 생성
CREATE TABLE BOARD (
    BNO NUMBER CONSTRAINT BOARD_BNO_PK PRIMARY KEY,
    MID VARCHAR2(40) CONSTRAINT MID_FK REFERENCES MEMBERS(MID),
    TITLE VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(1000) NOT NULL,
    CRE_DATE DATE NOT NULL,
    MOD_DATE DATE NOT NULL
);

COMMENT ON TABLE BOARD IS '게시판정보';
COMMENT ON COLUMN BOARD.BNO IS '게시판번호';
COMMENT ON COLUMN BOARD.MID IS '아이디';
COMMENT ON COLUMN BOARD.TITLE IS '제목';
COMMENT ON COLUMN BOARD.CONTENT IS '내용';
COMMENT ON COLUMN BOARD.CRE_DATE IS '생성날짜';
COMMENT ON COLUMN BOARD.MOD_DATE IS '수정날짜';

-------------------------시퀀스 생성
CREATE SEQUENCE  "NAVER"."MEMBERS_MNO_SEQ"  
    MINVALUE 1 
    MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1
    CACHE 20 NOORDER  NOCYCLE;
    
CREATE SEQUENCE  "NAVER"."BOARD_BNO_SEQ"  
    MINVALUE 1 
    MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 
    START WITH 1
    CACHE 20 NOORDER  NOCYCLE;

COMMIT;