-- test용
--id: psu0007
--pwd: psu0000!
--name: 박성욱

INSERT INTO MEMBERS
VALUES(MEMBERS_MNO_SEQ.nextval, 'AAA', 'AAA', 'AAA', SYSDATE, 'AAA@', SYSDATE, SYSDATE);
INSERT INTO MEMBERS
VALUES(MEMBERS_MNO_SEQ.nextval, 'BBB', 'BBB', 'BBB', SYSDATE, 'BBB@', SYSDATE, SYSDATE);
INSERT INTO MEMBERS
VALUES(MEMBERS_MNO_SEQ.nextval, 'CCC', 'CCC', 'CCC', SYSDATE, 'CCC@', SYSDATE, SYSDATE);
INSERT INTO MEMBERS
VALUES(MEMBERS_MNO_SEQ.nextval, 'DDD', 'DDD', 'DDD', SYSDATE, 'DDD@', SYSDATE, SYSDATE);

INSERT INTO BOARD
VALUES(BOARD_BNO_SEQ.nextval, 'AAA', '안녕하세요1', '안녕하세요', SYSDATE, SYSDATE);
INSERT INTO BOARD
VALUES(BOARD_BNO_SEQ.nextval, 'AAA', '안녕하세요2', '안녕하세요', SYSDATE, SYSDATE);
INSERT INTO BOARD
VALUES(BOARD_BNO_SEQ.nextval, 'AAA', '안녕하세요3', '안녕하세요', SYSDATE, SYSDATE);
INSERT INTO BOARD
VALUES(BOARD_BNO_SEQ.nextval, 'AAA', '안녕하세요4', '안녕하세요', SYSDATE, SYSDATE);
INSERT INTO BOARD
VALUES(BOARD_BNO_SEQ.nextval, 'AAA', '안녕하세요5', '안녕하세요', SYSDATE, SYSDATE);

INSERT INTO BOARD
VALUES(BOARD_BNO_SEQ.nextval, 'BBB', 'hello1', '반갑습니다', SYSDATE, SYSDATE);
INSERT INTO BOARD
VALUES(BOARD_BNO_SEQ.nextval, 'BBB', 'hello2', '반갑습니다', SYSDATE, SYSDATE);
INSERT INTO BOARD
VALUES(BOARD_BNO_SEQ.nextval, 'BBB', 'hello3', '반갑습니다', SYSDATE, SYSDATE);
INSERT INTO BOARD
VALUES(BOARD_BNO_SEQ.nextval, 'BBB', 'hello4', '반갑습니다', SYSDATE, SYSDATE);
INSERT INTO BOARD
VALUES(BOARD_BNO_SEQ.nextval, 'BBB', 'hello5', '반갑습니다', SYSDATE, SYSDATE);

INSERT INTO BOARD
VALUES(BOARD_BNO_SEQ.nextval, 'CCC', 'ezen안녕1', '안녕하세요', SYSDATE, SYSDATE);
INSERT INTO BOARD
VALUES(BOARD_BNO_SEQ.nextval, 'CCC', 'ezen안녕2', '안녕하세요', SYSDATE, SYSDATE);
INSERT INTO BOARD
VALUES(BOARD_BNO_SEQ.nextval, 'CCC', 'ezen안녕3', '안녕하세요', SYSDATE, SYSDATE);
INSERT INTO BOARD
VALUES(BOARD_BNO_SEQ.nextval, 'CCC', 'ezen안녕4', '안녕하세요', SYSDATE, SYSDATE);
INSERT INTO BOARD
VALUES(BOARD_BNO_SEQ.nextval, 'CCC', 'ezen안녕5', '안녕하세요', SYSDATE, SYSDATE);

INSERT INTO BOARD
VALUES(BOARD_BNO_SEQ.nextval, 'DDD', 'hahaha1', 'hahaha', SYSDATE, SYSDATE);
INSERT INTO BOARD
VALUES(BOARD_BNO_SEQ.nextval, 'DDD', 'hahaha2', 'hahaha', SYSDATE, SYSDATE);
INSERT INTO BOARD
VALUES(BOARD_BNO_SEQ.nextval, 'DDD', 'hahaha3', 'hahaha', SYSDATE, SYSDATE);
INSERT INTO BOARD
VALUES(BOARD_BNO_SEQ.nextval, 'DDD', 'hahaha4', 'hahaha', SYSDATE, SYSDATE);
INSERT INTO BOARD
VALUES(BOARD_BNO_SEQ.nextval, 'DDD', 'hahaha5', 'hahaha', SYSDATE, SYSDATE);

COMMIT;